kind: pipeline
name: default

steps:
  - name: publish
    image: djcass44/drone-helm-s3:latest
    pull: always
    settings:
      aws_access_key:
        from_secret: AWS_ACCESS_KEY
      aws_secret_key:
        from_secret: AWS_SECRET_KEY
      aws_region: ap-southeast-2
      s3_bucket: dev.castive.helm
      s3_path: charts
      chart_name: jmp-helm