apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.api }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicas.api }}
  selector:
    matchLabels:
      app: {{ .Values.name.api }}
  template:
    metadata:
      labels:
        app: {{ .Values.name.api }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 100
        runAsUser: 100
        runAsGroup: 101
      volumes:
      {{ if .Values.claimName }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.claimName }}
      {{ end }}
      - name: tmp
        emptyDir: {}
      containers:
      - env:
        {{- range $key, $value := .Values.db }}
        - name: {{ $key }}
          value:  {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.ssl }}
        - name: {{ $key }}
          value:  {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value:  {{ $value | quote }}
        {{- end }}
        - name: KEY_REALM
          value: {{ .Values.key.realm }}
        {{ if eq .Values.key.realm "aws-ssm" }}
        - name: KEY_AWS_SSM_NAME
          value: {{ .Values.key.aws.name }}
        {{ end }}
        image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
        imagePullPolicy: {{ .Values.images.api.pullPolicy }}
        name: {{ .Values.name.api }}
        ports:
        - containerPort: {{ .Values.env.PORT }}
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        {{ if .Values.claimName }}
        - mountPath: {{ .Values.env.JMP_HOME | quote }}
          name: data
        {{ end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /api/v3/health
            port: {{ .Values.env.PORT }}
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.ui }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.replicas.ui }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ .Values.name.ui }}
  template:
    metadata:
      labels:
        app: {{ .Values.name.ui }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 100
        runAsUser: 101
        runAsGroup: 101
      volumes:
      - name: tmp
        emptyDir: {}  
      containers:
      - image: "{{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}"
        imagePullPolicy: {{ .Values.images.ui.pullPolicy }}
        name: {{ .Values.name.ui }}
        env:
          - name: JMP_API_URL
            value: {{ index .Values.ingress.hosts 0 }}
          - name: JMP_API_SECURE
            value: "true"
          {{- with .Values.brand }}
          - name: JMP_BRAND_NAME
            value: {{ .name }}
          - name: JMP_BRAND_MSG
            value: {{ .msg }}
          - name: JMP_BRAND_NOUN
            value: {{ .noun }}
          - name: JMP_BRAND_KEY
            value: {{ .key }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: tmp
          mountPath: /var/tmp/nginx
        resources:
          requests:
            memory: 3Mi
            cpu: 10m
          limits:
            memory: 10Mi
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
      restartPolicy: Always