apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name.api }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name.api }}
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.port.api }}
    - protocol: TCP
      port: {{ .Values.port.ws }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name.ui }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name.ui }}
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 80