apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name.api }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name.api }}
  ingress:
  - from:
      - podSelector:
          matchLabels:
            {{- range $key, $val := .Values.netsec.source }}
            {{ $key }}: {{ $val }}
            {{- end}}
    ports:
    - protocol: TCP
      port: {{ .Values.port.api }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name.ui }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name.ui }}
  ingress:
  - from:
      - podSelector:
          matchLabels:
            {{- range $key, $val := .Values.netsec.source }}
            {{ $key }}: {{ $val }}
            {{- end}}
    ports:
    - protocol: TCP
      port: 8080