apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name.api }}
  name: {{ .Values.name.api }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port.api }}
    targetPort: {{ .Values.port.api }}
  - name: ws
    port: {{ .Values.port.ws }}
    targetPort: {{ .Values.port.ws }}
  selector:
    app: {{ .Values.name.api }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name.ui }}
  name: {{ .Values.name.ui }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ .Values.name.ui }}