apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name.api }}
  name: {{ .Values.name.api }}
spec:
  type: ClusterIP
  sessionAffinity: "ClientIP"
  ports:
  - name: http
    port: {{ .Values.port.api }}
    targetPort: {{ .Values.port.api }}
  selector:
    app: {{ .Values.name.api }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name.ui }}
  name: {{ .Values.name.ui }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.name.ui }}