apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name.api }}
  name: {{ .Values.name.api }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7000
    targetPort: 7000
  - name: ws
    port: {{ .Values.port.ws }}
    targetPort: {{ .Values.port.ws }}
  selector:
    app: {{ .Values.name.api }}
status:
  loadBalancer: {}